# -*- mode: ruby -*-
# vi: set ft=ruby :

# Override host locale in SSH session
ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure(2) do |config|

  # vagrant-cachier configuration
  # to install run: 'vagrant plugin install vagrant-cachier'
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
    config.cache.auto_detect = true
    # optionally enable NFS to speedup virtualbox shares
    #
    # config.cache.synced_folder_opts = {
    #   type: :nfs,
    #   mount_options: ['rw', 'vers=3', 'tcp', 'nolock']
    # }
  end

  # enable host only network (needed for NFS shares)
  # config.vm.network "private_network", type: "dhcp"

  # define machines
  machines = []
  machines << { name: "trusty", box: "ubuntu/trusty64" }

  # iterate through machines
  machines.each do |machine|
    # define config for given machine
    config.vm.define machine[:name] do |conf|
      # don't check for box updates (slow)
      conf.vm.box_check_update = false

      # specify base box
      conf.vm.box = machine[:box]

      # set box hostname
      conf.vm.hostname = machine[:name]

      conf.vm.provider "virtualbox" do |v|
        v.gui = false
        v.memory = 512
        v.cpus = 1

        # make DNS lookups faster by using host's DNS resolver
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]

        ## add extra disk for testing external volumes
        #disk = "./#{machine[:name]}_second_disk.vdi"
        #unless File.exist?(disk)
        #  v.customize ['createhd', '--filename', disk, '--size', 10 * 1024]
        #end
        #v.customize ['storageattach', :id, '--storagectl', 'SATAController',
        #             '--port', 1, '--device', 0,
        #             '--type', 'hdd', '--medium', disk]

        # use linked clone on newer vagrant
        v.linked_clone = true if Vagrant::VERSION =~ /^1.8/
      end

      # provision all machines together, after last machine is up
      if machine == machines.last
        conf.vm.provision :ansible do |ansible|
          ansible.playbook = "test.yml"
          ansible.limit = "all"
          ansible.verbose = "v"
          ansible.raw_arguments = "--diff"
        end
      end
    end
  end
end
